name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build-exam-app
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: cd frontend 
    - run: pwd
    - run: ls .
    - run: npm i --config frontend/package.json
    - run: npm run build --if-present  --config frontend/package.json
    - run: docker build . --file Dockerfile --tag online-exam:$(date +%s)
